//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldWordBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public int word_id { get; set; }
        public int group_id { get; set; }
        public string word_eng { get; set; }
        public string word_tr { get; set; }
    }
}
